CREATE DATABASE IF NOT EXISTS ecus5
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE ecus5;

SET GLOBAL time_zone = '+07:00';

CREATE TABLE IF NOT EXISTS _init_test (
  id INT PRIMARY KEY AUTO_INCREMENT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
